export const destinations = [
  {
    id: "1",
    name: "Rajasthan, Jaipur",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    rating: 4.9,
    reviews: 8421,
    budget: 15000,
    duration: "5 din",
    crowd: 68,
    tags: ["Heritage", "Royal", "Culture"],
    description: "Pink City ki shaan — majestic forts, vibrant bazaars, aur Rajputana culture ka anokha sangam.",
    country: "India",
    state: "Rajasthan",
    bestTime: "Oct-Mar",
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
    itinerary: [],
  },
  {
    id: "2",
    name: "Kerala Backwaters",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    rating: 4.8,
    reviews: 6234,
    budget: 18000,
    duration: "6 din",
    crowd: 45,
    tags: ["Nature", "Peaceful", "Ayurveda"],
    description: "God's Own Country — shikara rides, coconut groves, aur Ayurvedic spa ka perfect combination.",
    country: "India",
    state: "Kerala",
    bestTime: "Sep-Mar",
    highlights: ["Alleppey Houseboat", "Munnar Tea Gardens", "Kovalam Beach", "Periyar Wildlife"],
    itinerary: [],
  },
  {
    id: "3",
    name: "Goa Beaches",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    rating: 4.7,
    reviews: 12450,
    budget: 12000,
    duration: "4 din",
    crowd: 78,
    tags: ["Beach", "Party", "Adventure"],
    description: "Sun, sand, aur susegad — Goa ka vibe hi alag hai! North Goa ki party se South Goa ki peace tak.",
    country: "India",
    state: "Goa",
    bestTime: "Nov-Feb",
    highlights: ["Baga Beach", "Dudhsagar Falls", "Old Goa Churches", "Anjuna Flea Market"],
    itinerary: [],
  },
  {
    id: "4",
    name: "Himachal Pradesh, Manali",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    rating: 4.8,
    reviews: 9876,
    budget: 20000,
    duration: "7 din",
    crowd: 55,
    tags: ["Mountains", "Adventure", "Snow"],
    description: "Barf se dhaki pahaadiyan, Rohtang Pass ka thrill, aur Solang Valley mein adventure — Manali ek sapna hai!",
    country: "India",
    state: "Himachal Pradesh",
    bestTime: "Oct-Jun",
    highlights: ["Rohtang Pass", "Solang Valley", "Hadimba Temple", "Old Manali"],
    itinerary: [],
  },
  {
    id: "5",
    name: "Varanasi, Uttar Pradesh",
    image: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80",
    rating: 4.9,
    reviews: 7654,
    budget: 8000,
    duration: "3 din",
    crowd: 82,
    tags: ["Spiritual", "Culture", "Heritage"],
    description: "Duniya ka sabse purana shehar — Ganga ki aarti, ghats ki raunak, aur moksha ki talaash.",
    country: "India",
    state: "Uttar Pradesh",
    bestTime: "Oct-Mar",
    highlights: ["Ganga Aarti", "Kashi Vishwanath", "Sarnath", "Boat Ride"],
    itinerary: [],
  },
  {
    id: "6",
    name: "Andaman Islands",
    image: "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800&q=80",
    rating: 4.9,
    reviews: 4521,
    budget: 35000,
    duration: "6 din",
    crowd: 35,
    tags: ["Beach", "Diving", "Luxury"],
    description: "Neele paani, safed reti, aur coral reefs — Andaman India ka hidden paradise hai!",
    country: "India",
    state: "Andaman & Nicobar",
    bestTime: "Oct-May",
    highlights: ["Radhanagar Beach", "Scuba Diving", "Cellular Jail", "Neil Island"],
    itinerary: [],
  },
  {
    id: "7",
    name: "Ladakh, J&K",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    rating: 5.0,
    reviews: 5432,
    budget: 28000,
    duration: "8 din",
    crowd: 40,
    tags: ["Adventure", "Mountains", "Spiritual"],
    description: "Land of High Passes — Pangong Lake ka neela paani, monasteries ki shanti, aur biker's paradise!",
    country: "India",
    state: "Ladakh",
    bestTime: "Jun-Sep",
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La", "Thiksey Monastery"],
    itinerary: [],
  },
  {
    id: "8",
    name: "Coorg, Karnataka",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.7,
    reviews: 3876,
    budget: 14000,
    duration: "4 din",
    crowd: 42,
    tags: ["Nature", "Coffee", "Trekking"],
    description: "Scotland of India — coffee plantations, misty hills, aur Abbey Falls ki khubsurti.",
    country: "India",
    state: "Karnataka",
    bestTime: "Oct-Mar",
    highlights: ["Abbey Falls", "Dubare Elephant Camp", "Talakaveri", "Coffee Estates"],
    itinerary: [],
  },
  {
    id: "9",
    name: "Agra, Taj Mahal",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    rating: 4.9,
    reviews: 15000,
    budget: 10000,
    duration: "2 din",
    crowd: 90,
    tags: ["Heritage", "UNESCO", "Romance"],
    description: "Duniya ke saat ajoobe mein se ek — Taj Mahal ka safed sangmarmar aur Mughal architecture ka jaadu.",
    country: "India",
    state: "Uttar Pradesh",
    bestTime: "Oct-Mar",
    highlights: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh"],
    itinerary: [],
  },
  {
    id: "10",
    name: "Rishikesh & Haridwar",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    rating: 4.8,
    reviews: 6800,
    budget: 9000,
    duration: "4 din",
    crowd: 65,
    tags: ["Spiritual", "Adventure", "Yoga"],
    description: "Yoga capital of the world — Ganga ke kinare meditation, river rafting, aur Ganga aarti ka anubhav.",
    country: "India",
    state: "Uttarakhand",
    bestTime: "Sep-Jun",
    highlights: ["Laxman Jhula", "Har Ki Pauri", "River Rafting", "Neelkanth Temple"],
    itinerary: [],
  },
  {
    id: "11",
    name: "Udaipur, Rajasthan",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    rating: 4.8,
    reviews: 7200,
    budget: 16000,
    duration: "4 din",
    crowd: 60,
    tags: ["Heritage", "Romantic", "Lakes"],
    description: "City of Lakes — Lake Pichola pe boat ride, City Palace ki grandeur, aur romantic sunsets.",
    country: "India",
    state: "Rajasthan",
    bestTime: "Oct-Mar",
    highlights: ["Lake Pichola", "City Palace", "Jag Mandir", "Sajjangarh Fort"],
    itinerary: [],
  },
  {
    id: "12",
    name: "Darjeeling, West Bengal",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
    rating: 4.7,
    reviews: 4300,
    budget: 12000,
    duration: "4 din",
    crowd: 50,
    tags: ["Mountains", "Tea", "Scenic"],
    description: "Queen of Hills — Kanchenjunga ka nazara, toy train ki sair, aur world-famous Darjeeling tea.",
    country: "India",
    state: "West Bengal",
    bestTime: "Mar-May",
    highlights: ["Tiger Hill Sunrise", "Toy Train", "Tea Gardens", "Batasia Loop"],
    itinerary: [],
  },
  {
    id: "13",
    name: "Mysore, Karnataka",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.7,
    reviews: 5600,
    budget: 11000,
    duration: "3 din",
    crowd: 55,
    tags: ["Heritage", "Culture", "Palaces"],
    description: "City of Palaces — Mysore Palace ki illumination, Dasara festival, aur silk sarees ki shopping.",
    country: "India",
    state: "Karnataka",
    bestTime: "Oct-Feb",
    highlights: ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens", "Devaraja Market"],
    itinerary: [],
  },
  {
    id: "14",
    name: "Shimla, Himachal Pradesh",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    rating: 4.6,
    reviews: 8900,
    budget: 13000,
    duration: "4 din",
    crowd: 70,
    tags: ["Mountains", "Colonial", "Snow"],
    description: "Queen of Hills — British era architecture, Mall Road ki walk, aur snow-covered peaks.",
    country: "India",
    state: "Himachal Pradesh",
    bestTime: "Dec-Feb",
    highlights: ["Mall Road", "Jakhu Temple", "Kufri", "Christ Church"],
    itinerary: [],
  },
  {
    id: "15",
    name: "Amritsar, Punjab",
    image: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800&q=80",
    rating: 4.9,
    reviews: 9100,
    budget: 8000,
    duration: "3 din",
    crowd: 75,
    tags: ["Spiritual", "Heritage", "Food"],
    description: "Golden Temple ki divinity, Wagah Border ki ceremony, aur Punjab ka authentic khana.",
    country: "India",
    state: "Punjab",
    bestTime: "Oct-Mar",
    highlights: ["Golden Temple", "Wagah Border", "Jallianwala Bagh", "Durgiana Temple"],
    itinerary: [],
  },
  {
    id: "16",
    name: "Munnar, Kerala",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    rating: 4.8,
    reviews: 5400,
    budget: 14000,
    duration: "4 din",
    crowd: 45,
    tags: ["Nature", "Tea", "Trekking"],
    description: "Harit pahaadiyon mein chai ke baagaan — Munnar ki thandi hawa aur scenic beauty.",
    country: "India",
    state: "Kerala",
    bestTime: "Sep-Mar",
    highlights: ["Tea Gardens", "Eravikulam NP", "Mattupetty Dam", "Echo Point"],
    itinerary: [],
  },
  {
    id: "17",
    name: "Jaisalmer, Rajasthan",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    rating: 4.8,
    reviews: 4800,
    budget: 13000,
    duration: "3 din",
    crowd: 48,
    tags: ["Desert", "Heritage", "Adventure"],
    description: "Golden City — Thar Desert mein camel safari, sand dunes pe sunset, aur Sonar Qila ki shaan.",
    country: "India",
    state: "Rajasthan",
    bestTime: "Oct-Feb",
    highlights: ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli", "Gadisar Lake"],
    itinerary: [],
  },
  {
    id: "18",
    name: "Ooty, Tamil Nadu",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.6,
    reviews: 6200,
    budget: 11000,
    duration: "3 din",
    crowd: 60,
    tags: ["Mountains", "Nature", "Scenic"],
    description: "Nilgiri Hills ki rani — toy train, botanical gardens, aur misty valleys ka anubhav.",
    country: "India",
    state: "Tamil Nadu",
    bestTime: "Apr-Jun",
    highlights: ["Ooty Lake", "Botanical Gardens", "Doddabetta Peak", "Nilgiri Toy Train"],
    itinerary: [],
  },
  {
    id: "19",
    name: "Spiti Valley, Himachal",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    rating: 4.9,
    reviews: 2100,
    budget: 22000,
    duration: "7 din",
    crowd: 20,
    tags: ["Adventure", "Offbeat", "Himalayan"],
    description: "Cold desert mountain valley — ancient monasteries, snow leopards, aur starry skies at 12500ft.",
    country: "India",
    state: "Himachal Pradesh",
    bestTime: "Jun-Sep",
    highlights: ["Key Monastery", "Chandratal Lake", "Kaza Town", "Pin Valley NP"],
    itinerary: [],
  },
  {
    id: "20",
    name: "Hampi, Karnataka",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.8,
    reviews: 3900,
    budget: 10000,
    duration: "3 din",
    crowd: 35,
    tags: ["Heritage", "UNESCO", "Ruins"],
    description: "Vijayanagara Empire ki rajdhani — boulder landscapes mein ancient temples aur ruins.",
    country: "India",
    state: "Karnataka",
    bestTime: "Oct-Feb",
    highlights: ["Virupaksha Temple", "Vittala Temple", "Hampi Bazaar", "Matanga Hill"],
    itinerary: [],
  },
  {
    id: "21",
    name: "Rann of Kutch, Gujarat",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.7,
    reviews: 3200,
    budget: 15000,
    duration: "4 din",
    crowd: 40,
    tags: ["Nature", "Culture", "Festival"],
    description: "White desert ka jadoo — Rann Utsav festival, flamingos, aur Kutchi handicrafts.",
    country: "India",
    state: "Gujarat",
    bestTime: "Nov-Feb",
    highlights: ["White Rann", "Rann Utsav", "Dholavira", "Kalo Dungar"],
    itinerary: [],
  },
  {
    id: "22",
    name: "Pondicherry",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.7,
    reviews: 4500,
    budget: 12000,
    duration: "3 din",
    crowd: 55,
    tags: ["Beach", "French", "Spiritual"],
    description: "French Riviera of the East — colorful streets, Auroville ashram, aur pristine beaches.",
    country: "India",
    state: "Puducherry",
    bestTime: "Oct-Mar",
    highlights: ["Promenade Beach", "Auroville", "French Quarter", "Sri Aurobindo Ashram"],
    itinerary: [],
  },
  {
    id: "23",
    name: "Khajuraho, Madhya Pradesh",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.7,
    reviews: 2800,
    budget: 9000,
    duration: "2 din",
    crowd: 30,
    tags: ["Heritage", "UNESCO", "Art"],
    description: "UNESCO World Heritage — intricate sculptures aur medieval temple architecture.",
    country: "India",
    state: "Madhya Pradesh",
    bestTime: "Oct-Mar",
    highlights: ["Western Temple Group", "Eastern Temples", "Sound & Light Show", "Panna NP"],
    itinerary: [],
  },
  {
    id: "24",
    name: "Leh, Ladakh",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    rating: 4.9,
    reviews: 4100,
    budget: 25000,
    duration: "6 din",
    crowd: 38,
    tags: ["Adventure", "Spiritual", "Himalayan"],
    description: "Roof of the World — Leh Palace, monasteries, aur high-altitude lakes ka anubhav.",
    country: "India",
    state: "Ladakh",
    bestTime: "Jun-Sep",
    highlights: ["Leh Palace", "Shanti Stupa", "Magnetic Hill", "Hall of Fame"],
    itinerary: [],
  },
  {
    id: "25",
    name: "Mahabalipuram, Tamil Nadu",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.6,
    reviews: 3400,
    budget: 9000,
    duration: "2 din",
    crowd: 45,
    tags: ["Heritage", "Beach", "UNESCO"],
    description: "Shore Temple aur rock-cut caves — Pallava dynasty ki architectural masterpieces.",
    country: "India",
    state: "Tamil Nadu",
    bestTime: "Oct-Mar",
    highlights: ["Shore Temple", "Arjuna Penance", "Five Rathas", "Crocodile Bank"],
    itinerary: [],
  },
  {
    id: "26",
    name: "Kaziranga, Assam",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.8,
    reviews: 2600,
    budget: 16000,
    duration: "3 din",
    crowd: 25,
    tags: ["Wildlife", "UNESCO", "Nature"],
    description: "One-horned rhinoceros ka ghar — UNESCO World Heritage wildlife sanctuary.",
    country: "India",
    state: "Assam",
    bestTime: "Nov-Apr",
    highlights: ["Rhino Safari", "Elephant Safari", "Kohora Range", "Bagori Range"],
    itinerary: [],
  },
  {
    id: "27",
    name: "Pushkar, Rajasthan",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    rating: 4.7,
    reviews: 3800,
    budget: 8000,
    duration: "2 din",
    crowd: 55,
    tags: ["Spiritual", "Culture", "Festival"],
    description: "Brahma Temple aur Pushkar Lake — camel fair aur spiritual vibes ka unique combination.",
    country: "India",
    state: "Rajasthan",
    bestTime: "Oct-Nov",
    highlights: ["Brahma Temple", "Pushkar Lake", "Camel Fair", "Savitri Temple"],
    itinerary: [],
  },
  {
    id: "28",
    name: "Alleppey, Kerala",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    rating: 4.8,
    reviews: 5100,
    budget: 16000,
    duration: "3 din",
    crowd: 50,
    tags: ["Backwaters", "Houseboat", "Nature"],
    description: "Venice of the East — houseboat mein raat, backwater cruise, aur Kerala cuisine.",
    country: "India",
    state: "Kerala",
    bestTime: "Sep-Mar",
    highlights: ["Houseboat Stay", "Vembanad Lake", "Alappuzha Beach", "Kuttanad Fields"],
    itinerary: [],
  },
  {
    id: "29",
    name: "Nainital, Uttarakhand",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    rating: 4.7,
    reviews: 5800,
    budget: 11000,
    duration: "3 din",
    crowd: 65,
    tags: ["Mountains", "Lakes", "Nature"],
    description: "Lake District of India — Naini Lake pe boating, Snow View Point, aur Mall Road.",
    country: "India",
    state: "Uttarakhand",
    bestTime: "Mar-Jun",
    highlights: ["Naini Lake", "Snow View Point", "Tiffin Top", "Naina Devi Temple"],
    itinerary: [],
  },
  {
    id: "30",
    name: "Jodhpur, Rajasthan",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    rating: 4.8,
    reviews: 4600,
    budget: 12000,
    duration: "3 din",
    crowd: 58,
    tags: ["Heritage", "Blue City", "Culture"],
    description: "Blue City — Mehrangarh Fort ki grandeur, blue-painted houses, aur Rajasthani cuisine.",
    country: "India",
    state: "Rajasthan",
    bestTime: "Oct-Mar",
    highlights: ["Mehrangarh Fort", "Jaswant Thada", "Clock Tower", "Umaid Bhawan"],
    itinerary: [],
  },
  {
    id: "31",
    name: "Puri, Odisha",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.7,
    reviews: 6200,
    budget: 9000,
    duration: "3 din",
    crowd: 70,
    tags: ["Spiritual", "Beach", "Heritage"],
    description: "Jagannath Temple aur golden beach — Rath Yatra festival aur Odisha cuisine.",
    country: "India",
    state: "Odisha",
    bestTime: "Oct-Feb",
    highlights: ["Jagannath Temple", "Puri Beach", "Konark Sun Temple", "Chilika Lake"],
    itinerary: [],
  },
  {
    id: "32",
    name: "Shillong, Meghalaya",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
    rating: 4.7,
    reviews: 2900,
    budget: 13000,
    duration: "4 din",
    crowd: 30,
    tags: ["Mountains", "Waterfalls", "Culture"],
    description: "Scotland of the East — living root bridges, Cherrapunji waterfalls, aur Khasi culture.",
    country: "India",
    state: "Meghalaya",
    bestTime: "Oct-May",
    highlights: ["Elephant Falls", "Ward Lake", "Cherrapunji", "Living Root Bridges"],
    itinerary: [],
  },
  {
    id: "33",
    name: "Tirupati, Andhra Pradesh",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.9,
    reviews: 18000,
    budget: 7000,
    duration: "2 din",
    crowd: 95,
    tags: ["Spiritual", "Pilgrimage", "Heritage"],
    description: "Duniya ka sabse ameer temple — Venkateswara Swamy ke darshan aur Tirumala hills.",
    country: "India",
    state: "Andhra Pradesh",
    bestTime: "Oct-Mar",
    highlights: ["Tirumala Temple", "Padmavathi Temple", "Kapila Theertham", "ISKCON Temple"],
    itinerary: [],
  },
  {
    id: "34",
    name: "Mahabaleshwar, Maharashtra",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.6,
    reviews: 5400,
    budget: 12000,
    duration: "3 din",
    crowd: 60,
    tags: ["Mountains", "Strawberry", "Scenic"],
    description: "Strawberry capital of India — scenic viewpoints, Venna Lake, aur fresh strawberries.",
    country: "India",
    state: "Maharashtra",
    bestTime: "Feb-May",
    highlights: ["Venna Lake", "Arthur Seat", "Mapro Garden", "Pratapgad Fort"],
    itinerary: [],
  },
  {
    id: "35",
    name: "Vaishno Devi, J&K",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    rating: 4.9,
    reviews: 12000,
    budget: 10000,
    duration: "3 din",
    crowd: 80,
    tags: ["Spiritual", "Pilgrimage", "Trekking"],
    description: "Mata Vaishno Devi ki yatra — Trikuta Mountains mein divine darshan.",
    country: "India",
    state: "Jammu & Kashmir",
    bestTime: "Mar-Oct",
    highlights: ["Vaishno Devi Cave", "Bhairon Temple", "Katra Town", "Shiv Khori"],
    itinerary: [],
  },
  {
    id: "36",
    name: "Aurangabad, Maharashtra",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.7,
    reviews: 4100,
    budget: 12000,
    duration: "3 din",
    crowd: 45,
    tags: ["Heritage", "UNESCO", "Caves"],
    description: "Ajanta-Ellora caves ka shehar — Buddhist, Hindu, aur Jain rock-cut architecture.",
    country: "India",
    state: "Maharashtra",
    bestTime: "Oct-Mar",
    highlights: ["Ajanta Caves", "Ellora Caves", "Bibi Ka Maqbara", "Daulatabad Fort"],
    itinerary: [],
  },
  {
    id: "37",
    name: "Kolkata, West Bengal",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
    rating: 4.7,
    reviews: 7800,
    budget: 10000,
    duration: "4 din",
    crowd: 72,
    tags: ["Culture", "Heritage", "Food"],
    description: "City of Joy — Victoria Memorial, Howrah Bridge, aur Bengali cuisine ka anubhav.",
    country: "India",
    state: "West Bengal",
    bestTime: "Oct-Mar",
    highlights: ["Victoria Memorial", "Howrah Bridge", "Dakshineswar Temple", "Park Street"],
    itinerary: [],
  },
  {
    id: "38",
    name: "Hyderabad, Telangana",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.7,
    reviews: 8900,
    budget: 11000,
    duration: "3 din",
    crowd: 68,
    tags: ["Heritage", "Food", "Culture"],
    description: "City of Pearls — Charminar, Golconda Fort, aur world-famous Hyderabadi biryani.",
    country: "India",
    state: "Telangana",
    bestTime: "Oct-Feb",
    highlights: ["Charminar", "Golconda Fort", "Hussain Sagar", "Ramoji Film City"],
    itinerary: [],
  },
  {
    id: "39",
    name: "Kochi, Kerala",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    rating: 4.8,
    reviews: 5600,
    budget: 13000,
    duration: "3 din",
    crowd: 55,
    tags: ["Heritage", "Beach", "Culture"],
    description: "Queen of Arabian Sea — Fort Kochi, Chinese fishing nets, aur spice markets.",
    country: "India",
    state: "Kerala",
    bestTime: "Sep-Mar",
    highlights: ["Fort Kochi", "Chinese Fishing Nets", "Mattancherry Palace", "Jew Town"],
    itinerary: [],
  },
  {
    id: "40",
    name: "Bhopal, Madhya Pradesh",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.5,
    reviews: 3200,
    budget: 9000,
    duration: "3 din",
    crowd: 40,
    tags: ["Heritage", "Lakes", "Culture"],
    description: "City of Lakes — Bhimbetka caves, Sanchi Stupa, aur Upper Lake ki beauty.",
    country: "India",
    state: "Madhya Pradesh",
    bestTime: "Oct-Mar",
    highlights: ["Bhimbetka Caves", "Sanchi Stupa", "Upper Lake", "Van Vihar NP"],
    itinerary: [],
  },
  {
    id: "41",
    name: "Gangtok, Sikkim",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
    rating: 4.8,
    reviews: 3100,
    budget: 16000,
    duration: "5 din",
    crowd: 35,
    tags: ["Mountains", "Scenic", "Culture"],
    description: "Kanchenjunga ka nazara — Buddhist monasteries, Tsomgo Lake, aur Nathula Pass.",
    country: "India",
    state: "Sikkim",
    bestTime: "Mar-May",
    highlights: ["Tsomgo Lake", "Nathula Pass", "Rumtek Monastery", "MG Marg"],
    itinerary: [],
  },
  {
    id: "42",
    name: "Ajmer, Rajasthan",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    rating: 4.7,
    reviews: 4800,
    budget: 8000,
    duration: "2 din",
    crowd: 65,
    tags: ["Spiritual", "Heritage", "Culture"],
    description: "Dargah Sharif ki ziyarat — Sufi saint Moinuddin Chishti ki dargah aur Ana Sagar Lake.",
    country: "India",
    state: "Rajasthan",
    bestTime: "Oct-Mar",
    highlights: ["Dargah Sharif", "Ana Sagar Lake", "Adhai Din Ka Jhonpra", "Taragarh Fort"],
    itinerary: [],
  },
  {
    id: "43",
    name: "Guwahati, Assam",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.6,
    reviews: 3400,
    budget: 11000,
    duration: "3 din",
    crowd: 45,
    tags: ["Spiritual", "Wildlife", "Culture"],
    description: "Gateway to Northeast — Kamakhya Temple, Brahmaputra river cruise, aur Assamese culture.",
    country: "India",
    state: "Assam",
    bestTime: "Oct-Apr",
    highlights: ["Kamakhya Temple", "Umananda Island", "Pobitora WLS", "Brahmaputra Cruise"],
    itinerary: [],
  },
  {
    id: "44",
    name: "Mathura & Vrindavan, UP",
    image: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80",
    rating: 4.8,
    reviews: 7600,
    budget: 7000,
    duration: "2 din",
    crowd: 78,
    tags: ["Spiritual", "Krishna", "Heritage"],
    description: "Lord Krishna ki janmabhoomi — Holi festival, Banke Bihari Temple, aur Yamuna aarti.",
    country: "India",
    state: "Uttar Pradesh",
    bestTime: "Oct-Mar",
    highlights: ["Krishna Janmabhoomi", "Banke Bihari Temple", "ISKCON Vrindavan", "Govardhan Hill"],
    itinerary: [],
  },
  {
    id: "45",
    name: "Lonavala, Maharashtra",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.5,
    reviews: 6800,
    budget: 9000,
    duration: "2 din",
    crowd: 70,
    tags: ["Mountains", "Waterfalls", "Weekend"],
    description: "Mumbai-Pune ke beech hill station — Bhushi Dam, Tiger Point, aur chikki ki shopping.",
    country: "India",
    state: "Maharashtra",
    bestTime: "Jun-Sep",
    highlights: ["Bhushi Dam", "Tiger Point", "Karla Caves", "Rajmachi Fort"],
    itinerary: [],
  },
  {
    id: "46",
    name: "Tawang, Arunachal Pradesh",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    rating: 4.9,
    reviews: 1200,
    budget: 20000,
    duration: "5 din",
    crowd: 15,
    tags: ["Offbeat", "Spiritual", "Himalayan"],
    description: "Arunachal ka hidden gem — Tawang Monastery, Sela Pass, aur Madhuri Lake.",
    country: "India",
    state: "Arunachal Pradesh",
    bestTime: "Mar-Oct",
    highlights: ["Tawang Monastery", "Sela Pass", "Madhuri Lake", "Nuranang Falls"],
    itinerary: [],
  },
  {
    id: "47",
    name: "Dwarka, Gujarat",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    rating: 4.7,
    reviews: 5200,
    budget: 9000,
    duration: "3 din",
    crowd: 60,
    tags: ["Spiritual", "Heritage", "Pilgrimage"],
    description: "Char Dham mein se ek — Dwarkadhish Temple aur Arabian Sea ka sangam.",
    country: "India",
    state: "Gujarat",
    bestTime: "Oct-Mar",
    highlights: ["Dwarkadhish Temple", "Bet Dwarka", "Nageshwar Jyotirlinga", "Rukmini Temple"],
    itinerary: [],
  },
  {
    id: "48",
    name: "Coimbatore, Tamil Nadu",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    rating: 4.5,
    reviews: 3800,
    budget: 10000,
    duration: "3 din",
    crowd: 50,
    tags: ["Nature", "Spiritual", "Gateway"],
    description: "Manchester of South India — Isha Yoga Center, Ooty gateway, aur Nilgiri hills.",
    country: "India",
    state: "Tamil Nadu",
    bestTime: "Oct-Mar",
    highlights: ["Isha Yoga Center", "Marudamalai Temple", "VOC Park", "Siruvani Waterfalls"],
    itinerary: [],
  },
  {
    id: "49",
    name: "Gokarna, Karnataka",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    rating: 4.7,
    reviews: 2800,
    budget: 11000,
    duration: "4 din",
    crowd: 30,
    tags: ["Beach", "Offbeat", "Spiritual"],
    description: "Goa ka chhota bhai — pristine beaches, Om Beach, aur Mahabaleshwar Temple.",
    country: "India",
    state: "Karnataka",
    bestTime: "Oct-Mar",
    highlights: ["Om Beach", "Kudle Beach", "Mahabaleshwar Temple", "Half Moon Beach"],
    itinerary: [],
  },
  {
    id: "50",
    name: "Ziro Valley, Arunachal",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    rating: 4.9,
    reviews: 800,
    budget: 18000,
    duration: "5 din",
    crowd: 10,
    tags: ["Offbeat", "Tribal", "Nature"],
    description: "UNESCO tentative heritage — Apatani tribe villages, paddy fields, aur zero tourists.",
    country: "India",
    state: "Arunachal Pradesh",
    bestTime: "Sep-Nov",
    highlights: ["Apatani Villages", "Ziro Music Festival", "Talley Valley WLS", "Dolo Mando"],
    itinerary: [],
  },
];
export const myTrips = [
  {
    id: 't1',
    destination: 'Rajasthan, Jaipur',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    startDate: '2026-06-15',
    endDate: '2026-06-20',
    duration: 5,
    budget: 15000,
    spent: 0,
    travelers: 2,
    status: 'upcoming',
    progress: 0,
    tags: ['Heritage', 'Royal'],
  },
  {
    id: 't2',
    destination: 'Kerala Backwaters',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    startDate: '2026-05-01',
    endDate: '2026-05-07',
    duration: 6,
    budget: 18000,
    spent: 11000,
    travelers: 2,
    status: 'ongoing',
    progress: 60,
    tags: ['Nature', 'Peaceful'],
  },
  {
    id: 't3',
    destination: 'Goa Beaches',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    startDate: '2026-01-10',
    endDate: '2026-01-14',
    duration: 4,
    budget: 12000,
    spent: 11500,
    travelers: 4,
    status: 'completed',
    progress: 100,
    tags: ['Beach', 'Party'],
  },
  {
    id: 't4',
    destination: 'Ladakh, J&K',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    startDate: '2026-07-20',
    endDate: '2026-07-28',
    duration: 8,
    budget: 28000,
    spent: 0,
    travelers: 3,
    status: 'upcoming',
    progress: 0,
    tags: ['Adventure', 'Mountains'],
  },
];

export const bookings = [
  {
    id: 'b1',
    type: 'hotel',
    name: 'Rambagh Palace, Jaipur',
    destination: 'Jaipur, Rajasthan',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    checkIn: '2026-06-15',
    checkOut: '2026-06-20',
    guests: 2,
    amount: 12000,
    status: 'confirmed',
    bookingRef: 'HTL-IND-001',
    rating: 5,
  },
  {
    id: 'b2',
    type: 'flight',
    name: 'IndiGo 6E 204',
    destination: 'Delhi → Jaipur',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    checkIn: '2026-06-15',
    checkOut: '2026-06-15',
    guests: 2,
    amount: 4800,
    status: 'confirmed',
    bookingRef: 'FLT-IND-002',
    rating: 4,
  },
  {
    id: 'b3',
    type: 'activity',
    name: 'Amber Fort Elephant Ride',
    destination: 'Jaipur, Rajasthan',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    checkIn: '2026-06-16',
    checkOut: '2026-06-16',
    guests: 2,
    amount: 1200,
    status: 'pending',
    bookingRef: 'ACT-IND-003',
    rating: 5,
  },
  {
    id: 'b4',
    type: 'hotel',
    name: 'Kumarakom Lake Resort',
    destination: 'Kumarakom, Kerala',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    checkIn: '2026-05-01',
    checkOut: '2026-05-07',
    guests: 2,
    amount: 22000,
    status: 'confirmed',
    bookingRef: 'HTL-IND-004',
    rating: 5,
  },
  {
    id: 'b5',
    type: 'flight',
    name: 'Air India AI 505',
    destination: 'Mumbai → Kochi',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    checkIn: '2026-05-01',
    checkOut: '2026-05-01',
    guests: 2,
    amount: 6500,
    status: 'confirmed',
    bookingRef: 'FLT-IND-005',
    rating: 4,
  },
];

export const alerts = [
  {
    id: 'a1',
    type: 'weather',
    severity: 'high',
    title: 'Monsoon Alert — Kerala',
    description: 'Heavy rainfall expected in Kerala June 1–15. Houseboat bookings may be affected. Alleppey backwaters could flood.',
    destination: 'Kerala',
    timestamp: '2026-05-09T08:30:00',
    actions: ['Reschedule houseboat', 'Check hotel policy', 'Travel insurance claim'],
    icon: '🌧️',
  },
  {
    id: 'a2',
    type: 'crowd',
    severity: 'medium',
    title: 'Bheed Alert — Amber Fort',
    description: 'Amber Fort mein June 16 ko 90% capacity expected. 2 ghante pehle pahuncho ya online ticket book karo.',
    destination: 'Jaipur, Rajasthan',
    timestamp: '2026-05-09T07:15:00',
    actions: ['Online ticket book karo', 'Subah jaldi jao', 'Guide hire karo'],
    icon: '👥',
  },
  {
    id: 'a3',
    type: 'pricing',
    severity: 'low',
    title: 'Price Drop — Manali Hotels',
    description: 'Manali mein July ke liye hotel prices 28% gir gayi hain. Abhi book karo aur bachat karo!',
    destination: 'Manali, Himachal Pradesh',
    timestamp: '2026-05-08T14:00:00',
    actions: ['Deals dekho', 'Room upgrade karo', 'Abhi book karo'],
    icon: '💰',
  },
  {
    id: 'a4',
    type: 'safety',
    severity: 'medium',
    title: 'Road Closure — Rohtang Pass',
    description: 'Rohtang Pass June 10–12 ke liye band rahega maintenance ke liye. Alternative route use karo.',
    destination: 'Manali, Himachal Pradesh',
    timestamp: '2026-05-08T10:00:00',
    actions: ['Alternative route dekho', 'HRTC helpline call karo', 'Itinerary update karo'],
    icon: '🛡️',
  },
  {
    id: 'a5',
    type: 'weather',
    severity: 'low',
    title: 'Perfect Weather — Ladakh',
    description: 'Ladakh mein July-August perfect weather hai. Pangong Lake aur Nubra Valley ke liye ideal time!',
    destination: 'Ladakh',
    timestamp: '2026-05-07T09:00:00',
    actions: ['Trip plan karo', 'Permit apply karo', 'Bike rent book karo'],
    icon: '☀️',
  },
];

export const communityPosts = [
  {
    id: 'p1',
    user: { name: 'Priya Sharma', avatar: 'https://randomuser.me/api/portraits/women/44.jpg', followers: 3240, verified: true },
    destination: 'Jaipur, Rajasthan',
    images: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    ],
    caption: 'Amber Fort ki ye shaam zindagi bhar yaad rahegi 🏰✨ Rajasthan ka har kona ek kahani sunata hai. Pink City ne dil jeet liya! #IncredibleIndia',
    likes: 4821,
    comments: 342,
    shares: 189,
    timestamp: '2026-05-08T18:30:00',
    tags: ['#Jaipur', '#Rajasthan', '#AmberFort', '#IncredibleIndia'],
    liked: false,
    saved: false,
  },
  {
    id: 'p2',
    user: { name: 'Arjun Mehta', avatar: 'https://randomuser.me/api/portraits/men/32.jpg', followers: 5670, verified: true },
    destination: 'Ladakh, J&K',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    caption: 'Pangong Lake ke kinare baith ke chai peena — ye feeling words mein nahi aa sakti 🏔️💙 Ladakh ek baar zaroor jao! #Ladakh #PangongLake',
    likes: 7234,
    comments: 521,
    shares: 298,
    timestamp: '2026-05-07T09:15:00',
    tags: ['#Ladakh', '#PangongLake', '#BikeTrip', '#Mountains'],
    liked: true,
    saved: true,
  },
  {
    id: 'p3',
    user: { name: 'Sneha Patel', avatar: 'https://randomuser.me/api/portraits/women/68.jpg', followers: 1892, verified: false },
    destination: 'Kerala Backwaters',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    ],
    caption: 'Houseboat mein ek raat — coconut trees, backwaters, aur stars 🌴⭐ Kerala truly is God\'s Own Country! Ayurveda massage ne toh soul refresh kar diya 🙏',
    likes: 3156,
    comments: 198,
    shares: 134,
    timestamp: '2026-05-06T14:45:00',
    tags: ['#Kerala', '#Backwaters', '#Houseboat', '#GodsOwnCountry'],
    liked: false,
    saved: true,
  },
  {
    id: 'p4',
    user: { name: 'Rahul Verma', avatar: 'https://randomuser.me/api/portraits/men/55.jpg', followers: 2340, verified: false },
    destination: 'Varanasi, UP',
    images: [
      'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80',
    ],
    caption: 'Ganga aarti dekh ke aankhein bhar aayi 🪔🙏 Varanasi sirf ek shehar nahi, ek anubhav hai. Har Indian ko ek baar zaroor aana chahiye! #Varanasi #GangaAarti',
    likes: 5892,
    comments: 412,
    shares: 267,
    timestamp: '2026-05-05T20:00:00',
    tags: ['#Varanasi', '#GangaAarti', '#Kashi', '#Spiritual'],
    liked: false,
    saved: false,
  },
];

export const priceTrends = [
  { month: 'Jan', flights: 4200, hotels: 2800, activities: 1200 },
  { month: 'Feb', flights: 3800, hotels: 2500, activities: 1100 },
  { month: 'Mar', flights: 5200, hotels: 3200, activities: 1500 },
  { month: 'Apr', flights: 6500, hotels: 4000, activities: 1800 },
  { month: 'May', flights: 5800, hotels: 3500, activities: 1600 },
  { month: 'Jun', flights: 4500, hotels: 2800, activities: 1300 },
  { month: 'Jul', flights: 5500, hotels: 3800, activities: 1700 },
  { month: 'Aug', flights: 5200, hotels: 3600, activities: 1600 },
  { month: 'Sep', flights: 4800, hotels: 3000, activities: 1400 },
  { month: 'Oct', flights: 6200, hotels: 4200, activities: 2000 },
  { month: 'Nov', flights: 7500, hotels: 5000, activities: 2400 },
  { month: 'Dec', flights: 8500, hotels: 6000, activities: 2800 },
];

export const crowdHeatmap = [
  { city: 'Goa', crowd: 92, trend: 'up' },
  { city: 'Jaipur', crowd: 75, trend: 'up' },
  { city: 'Manali', crowd: 68, trend: 'up' },
  { city: 'Kerala', crowd: 55, trend: 'stable' },
  { city: 'Varanasi', crowd: 82, trend: 'stable' },
  { city: 'Ladakh', crowd: 40, trend: 'down' },
  { city: 'Coorg', crowd: 45, trend: 'stable' },
  { city: 'Andaman', crowd: 35, trend: 'down' },
];

export const leaderboard = [
  { rank: 1, name: 'Vikram Singh', avatar: 'https://randomuser.me/api/portraits/men/10.jpg', trips: 52, states: 28, points: 15420 },
  { rank: 2, name: 'Ananya Krishnan', avatar: 'https://randomuser.me/api/portraits/women/11.jpg', trips: 44, states: 25, points: 13280 },
  { rank: 3, name: 'Rohan Gupta', avatar: 'https://randomuser.me/api/portraits/men/12.jpg', trips: 38, states: 22, points: 11640 },
  { rank: 4, name: 'Meera Nair', avatar: 'https://randomuser.me/api/portraits/women/13.jpg', trips: 31, states: 19, points: 9830 },
  { rank: 5, name: 'Aditya Joshi', avatar: 'https://randomuser.me/api/portraits/men/14.jpg', trips: 27, states: 16, points: 8180 },
];

export const suggestedPrompts = [
  '₹15,000 mein Rajasthan trip plan karo',
  'Kerala honeymoon package suggest karo',
  'Ladakh bike trip ke liye best route',
  'Goa mein budget-friendly stays',
  'Monsoon mein kahan jaana chahiye India mein?',
  'North East India hidden gems batao',
  'Family trip for Varanasi & Agra',
  'Solo travel tips for women in India',
];

export const weatherData = {
  city: 'Delhi',
  temp: 38,
  condition: 'Dhoop ke saath garmi',
  humidity: 45,
  wind: 18,
  icon: '☀️',
};

export const indianCities = [
  'Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata',
  'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow',
  'Kochi', 'Chandigarh', 'Bhopal', 'Indore', 'Surat',
];

export const tripTypes = [
  'Family Trip', 'Honeymoon', 'Solo Adventure', 'Friends Gang',
  'Pilgrimage', 'Hill Station', 'Beach Vacation', 'Heritage Tour',
  'Wildlife Safari', 'Backpacking',
];
