export const destinations = [
  {
    id: '1',
    name: 'Rajasthan, Jaipur',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    rating: 4.9,
    reviews: 8421,
    budget: 15000,
    duration: '5 din',
    crowd: 68,
    tags: ['Heritage', 'Royal', 'Culture'],
    description: 'Pink City ki shaan — majestic forts, vibrant bazaars, aur Rajputana culture ka anokha sangam.',
    country: 'India',
    state: 'Rajasthan',
    bestTime: 'Oct–Mar',
    highlights: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar'],
    itinerary: [
      { day: 1, title: 'Arrival & Pink City Darshan', activities: ['Hotel check-in', 'Hawa Mahal visit', 'Johari Bazaar shopping', 'Chokhi Dhani dinner'], hotels: ['Rambagh Palace'], budget: 3500 },
      { day: 2, title: 'Amber Fort & Nahargarh', activities: ['Amber Fort elephant ride', 'Nahargarh Fort sunset', 'Jal Mahal view', 'Lassi at LMB'], hotels: ['Rambagh Palace'], budget: 2800 },
      { day: 3, title: 'City Palace & Jantar Mantar', activities: ['City Palace tour', 'Jantar Mantar', 'Albert Hall Museum', 'Bapu Bazaar'], hotels: ['Rambagh Palace'], budget: 2200 },
      { day: 4, title: 'Day Trip to Pushkar', activities: ['Pushkar Lake', 'Brahma Temple', 'Camel ride', 'Pushkar Bazaar'], hotels: ['Rambagh Palace'], budget: 2500 },
      { day: 5, title: 'Departure', activities: ['Morning yoga', 'Last minute shopping', 'Airport/Station'], hotels: [], budget: 1000 },
    ],
  },
  {
    id: '2',
    name: 'Kerala Backwaters',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    rating: 4.8,
    reviews: 6234,
    budget: 18000,
    duration: '6 din',
    crowd: 45,
    tags: ['Nature', 'Peaceful', 'Ayurveda'],
    description: 'God\'s Own Country — shikara rides, coconut groves, aur Ayurvedic spa ka perfect combination.',
    country: 'India',
    state: 'Kerala',
    bestTime: 'Sep–Mar',
    highlights: ['Alleppey Houseboat', 'Munnar Tea Gardens', 'Kovalam Beach', 'Periyar Wildlife'],
    itinerary: [
      { day: 1, title: 'Kochi Arrival', activities: ['Fort Kochi walk', 'Chinese fishing nets', 'Kathakali show', 'Seafood dinner'], hotels: ['Brunton Boatyard'], budget: 3200 },
      { day: 2, title: 'Munnar Tea Gardens', activities: ['Tea plantation tour', 'Eravikulam National Park', 'Mattupetty Dam', 'Tea tasting'], hotels: ['Tea County Resort'], budget: 2800 },
      { day: 3, title: 'Alleppey Houseboat', activities: ['Houseboat check-in', 'Backwater cruise', 'Village walk', 'Sunset on water'], hotels: ['Premium Houseboat'], budget: 4500 },
      { day: 4, title: 'Kumarakom & Vembanad', activities: ['Bird sanctuary', 'Kayaking', 'Ayurvedic massage', 'Local cuisine'], hotels: ['Kumarakom Lake Resort'], budget: 3800 },
      { day: 5, title: 'Kovalam Beach', activities: ['Lighthouse Beach', 'Surfing', 'Ayurvedic spa', 'Seafood BBQ'], hotels: ['Leela Kovalam'], budget: 3500 },
      { day: 6, title: 'Departure', activities: ['Morning yoga', 'Coconut shopping', 'Trivandrum airport'], hotels: [], budget: 1200 },
    ],
  },
  {
    id: '3',
    name: 'Goa Beaches',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    rating: 4.7,
    reviews: 12450,
    budget: 12000,
    duration: '4 din',
    crowd: 78,
    tags: ['Beach', 'Party', 'Adventure'],
    description: 'Sun, sand, aur susegad — Goa ka vibe hi alag hai! North Goa ki party se South Goa ki peace tak.',
    country: 'India',
    state: 'Goa',
    bestTime: 'Nov–Feb',
    highlights: ['Baga Beach', 'Dudhsagar Falls', 'Old Goa Churches', 'Anjuna Flea Market'],
    itinerary: [
      { day: 1, title: 'North Goa Arrival', activities: ['Calangute Beach', 'Baga nightlife', 'Shacks dinner', 'Casino visit'], hotels: ['Taj Holiday Village'], budget: 3000 },
      { day: 2, title: 'Water Sports & Forts', activities: ['Parasailing at Baga', 'Aguada Fort', 'Anjuna Flea Market', 'Sunset cruise'], hotels: ['Taj Holiday Village'], budget: 2800 },
      { day: 3, title: 'South Goa & Dudhsagar', activities: ['Dudhsagar Falls trek', 'Palolem Beach', 'Colva Beach', 'Seafood dinner'], hotels: ['Alila Diwa Goa'], budget: 3200 },
      { day: 4, title: 'Old Goa & Departure', activities: ['Basilica of Bom Jesus', 'Spice plantation', 'Mapusa Market', 'Airport'], hotels: [], budget: 2000 },
    ],
  },
  {
    id: '4',
    name: 'Himachal Pradesh, Manali',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    rating: 4.8,
    reviews: 9876,
    budget: 20000,
    duration: '7 din',
    crowd: 55,
    tags: ['Mountains', 'Adventure', 'Snow'],
    description: 'Barf se dhaki pahaadiyan, Rohtang Pass ka thrill, aur Solang Valley mein adventure — Manali ek sapna hai!',
    country: 'India',
    state: 'Himachal Pradesh',
    bestTime: 'Oct–Jun',
    highlights: ['Rohtang Pass', 'Solang Valley', 'Hadimba Temple', 'Old Manali'],
    itinerary: [
      { day: 1, title: 'Manali Arrival', activities: ['Hotel check-in', 'Mall Road walk', 'Tibetan Market', 'Momos dinner'], hotels: ['The Himalayan'], budget: 3500 },
      { day: 2, title: 'Rohtang Pass', activities: ['Rohtang Pass snow', 'Skiing', 'Photography', 'Maggi at top'], hotels: ['The Himalayan'], budget: 4000 },
      { day: 3, title: 'Solang Valley', activities: ['Paragliding', 'Zorbing', 'Cable car', 'River rafting'], hotels: ['The Himalayan'], budget: 3800 },
      { day: 4, title: 'Kullu & Manikaran', activities: ['Kullu Dussehra ground', 'Manikaran hot springs', 'Gurudwara visit', 'Local food'], hotels: ['The Himalayan'], budget: 2500 },
      { day: 5, title: 'Old Manali & Hadimba', activities: ['Hadimba Temple', 'Vashisht hot springs', 'Old Manali cafes', 'Sunset point'], hotels: ['The Himalayan'], budget: 2200 },
      { day: 6, title: 'Spiti Valley Day Trip', activities: ['Spiti River view', 'Key Monastery', 'Kaza town', 'Stargazing'], hotels: ['The Himalayan'], budget: 3000 },
      { day: 7, title: 'Departure', activities: ['Morning trek', 'Souvenir shopping', 'Bus/Flight back'], hotels: [], budget: 1000 },
    ],
  },
  {
    id: '5',
    name: 'Varanasi, Uttar Pradesh',
    image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80',
    rating: 4.9,
    reviews: 7654,
    budget: 8000,
    duration: '3 din',
    crowd: 82,
    tags: ['Spiritual', 'Culture', 'Heritage'],
    description: 'Duniya ka sabse purana shehar — Ganga ki aarti, ghats ki raunak, aur moksha ki talaash.',
    country: 'India',
    state: 'Uttar Pradesh',
    bestTime: 'Oct–Mar',
    highlights: ['Ganga Aarti', 'Kashi Vishwanath', 'Sarnath', 'Boat Ride'],
    itinerary: [
      { day: 1, title: 'Ghats & Aarti', activities: ['Dashashwamedh Ghat aarti', 'Boat ride at sunrise', 'Kashi Vishwanath Temple', 'Banarasi paan'], hotels: ['BrijRama Palace'], budget: 2800 },
      { day: 2, title: 'Sarnath & Old City', activities: ['Sarnath Buddhist site', 'Dhamek Stupa', 'Silk weaving workshop', 'Banarasi thali'], hotels: ['BrijRama Palace'], budget: 2500 },
      { day: 3, title: 'Sunrise Boat & Departure', activities: ['Sunrise boat ride', 'Manikarnika Ghat', 'Chowk shopping', 'Station/Airport'], hotels: [], budget: 1500 },
    ],
  },
  {
    id: '6',
    name: 'Andaman Islands',
    image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800&q=80',
    rating: 4.9,
    reviews: 4521,
    budget: 35000,
    duration: '6 din',
    crowd: 35,
    tags: ['Beach', 'Diving', 'Luxury'],
    description: 'Neele paani, safed reti, aur coral reefs — Andaman India ka hidden paradise hai!',
    country: 'India',
    state: 'Andaman & Nicobar',
    bestTime: 'Oct–May',
    highlights: ['Radhanagar Beach', 'Scuba Diving', 'Cellular Jail', 'Neil Island'],
    itinerary: [],
  },
  {
    id: '7',
    name: 'Ladakh, J&K',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    rating: 5.0,
    reviews: 5432,
    budget: 28000,
    duration: '8 din',
    crowd: 40,
    tags: ['Adventure', 'Mountains', 'Spiritual'],
    description: 'Land of High Passes — Pangong Lake ka neela paani, monasteries ki shanti, aur biker\'s paradise!',
    country: 'India',
    state: 'Ladakh',
    bestTime: 'Jun–Sep',
    highlights: ['Pangong Lake', 'Nubra Valley', 'Khardung La', 'Thiksey Monastery'],
    itinerary: [],
  },
  {
    id: '8',
    name: 'Coorg, Karnataka',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
    rating: 4.7,
    reviews: 3876,
    budget: 14000,
    duration: '4 din',
    crowd: 42,
    tags: ['Nature', 'Coffee', 'Trekking'],
    description: 'Scotland of India — coffee plantations, misty hills, aur Abbey Falls ki khubsurti.',
    country: 'India',
    state: 'Karnataka',
    bestTime: 'Oct–Mar',
    highlights: ['Abbey Falls', 'Dubare Elephant Camp', 'Talakaveri', 'Coffee Estates'],
    itinerary: [],
  },
];

export const myTrips = [
  {
    id: 't1',
    destination: 'Rajasthan, Jaipur',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    startDate: '2026-06-15',
    endDate: '2026-06-20',
    duration: 5,
    budget: 15000,
    spent: 0,
    travelers: 2,
    status: 'upcoming',
    progress: 0,
    tags: ['Heritage', 'Royal'],
  },
  {
    id: 't2',
    destination: 'Kerala Backwaters',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    startDate: '2026-05-01',
    endDate: '2026-05-07',
    duration: 6,
    budget: 18000,
    spent: 11000,
    travelers: 2,
    status: 'ongoing',
    progress: 60,
    tags: ['Nature', 'Peaceful'],
  },
  {
    id: 't3',
    destination: 'Goa Beaches',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    startDate: '2026-01-10',
    endDate: '2026-01-14',
    duration: 4,
    budget: 12000,
    spent: 11500,
    travelers: 4,
    status: 'completed',
    progress: 100,
    tags: ['Beach', 'Party'],
  },
  {
    id: 't4',
    destination: 'Ladakh, J&K',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    startDate: '2026-07-20',
    endDate: '2026-07-28',
    duration: 8,
    budget: 28000,
    spent: 0,
    travelers: 3,
    status: 'upcoming',
    progress: 0,
    tags: ['Adventure', 'Mountains'],
  },
];

export const bookings = [
  {
    id: 'b1',
    type: 'hotel',
    name: 'Rambagh Palace, Jaipur',
    destination: 'Jaipur, Rajasthan',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    checkIn: '2026-06-15',
    checkOut: '2026-06-20',
    guests: 2,
    amount: 12000,
    status: 'confirmed',
    bookingRef: 'HTL-IND-001',
    rating: 5,
  },
  {
    id: 'b2',
    type: 'flight',
    name: 'IndiGo 6E 204',
    destination: 'Delhi → Jaipur',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    checkIn: '2026-06-15',
    checkOut: '2026-06-15',
    guests: 2,
    amount: 4800,
    status: 'confirmed',
    bookingRef: 'FLT-IND-002',
    rating: 4,
  },
  {
    id: 'b3',
    type: 'activity',
    name: 'Amber Fort Elephant Ride',
    destination: 'Jaipur, Rajasthan',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    checkIn: '2026-06-16',
    checkOut: '2026-06-16',
    guests: 2,
    amount: 1200,
    status: 'pending',
    bookingRef: 'ACT-IND-003',
    rating: 5,
  },
  {
    id: 'b4',
    type: 'hotel',
    name: 'Kumarakom Lake Resort',
    destination: 'Kumarakom, Kerala',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    checkIn: '2026-05-01',
    checkOut: '2026-05-07',
    guests: 2,
    amount: 22000,
    status: 'confirmed',
    bookingRef: 'HTL-IND-004',
    rating: 5,
  },
  {
    id: 'b5',
    type: 'flight',
    name: 'Air India AI 505',
    destination: 'Mumbai → Kochi',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    checkIn: '2026-05-01',
    checkOut: '2026-05-01',
    guests: 2,
    amount: 6500,
    status: 'confirmed',
    bookingRef: 'FLT-IND-005',
    rating: 4,
  },
];

export const alerts = [
  {
    id: 'a1',
    type: 'weather',
    severity: 'high',
    title: 'Monsoon Alert — Kerala',
    description: 'Heavy rainfall expected in Kerala June 1–15. Houseboat bookings may be affected. Alleppey backwaters could flood.',
    destination: 'Kerala',
    timestamp: '2026-05-09T08:30:00',
    actions: ['Reschedule houseboat', 'Check hotel policy', 'Travel insurance claim'],
    icon: '🌧️',
  },
  {
    id: 'a2',
    type: 'crowd',
    severity: 'medium',
    title: 'Bheed Alert — Amber Fort',
    description: 'Amber Fort mein June 16 ko 90% capacity expected. 2 ghante pehle pahuncho ya online ticket book karo.',
    destination: 'Jaipur, Rajasthan',
    timestamp: '2026-05-09T07:15:00',
    actions: ['Online ticket book karo', 'Subah jaldi jao', 'Guide hire karo'],
    icon: '👥',
  },
  {
    id: 'a3',
    type: 'pricing',
    severity: 'low',
    title: 'Price Drop — Manali Hotels',
    description: 'Manali mein July ke liye hotel prices 28% gir gayi hain. Abhi book karo aur bachat karo!',
    destination: 'Manali, Himachal Pradesh',
    timestamp: '2026-05-08T14:00:00',
    actions: ['Deals dekho', 'Room upgrade karo', 'Abhi book karo'],
    icon: '💰',
  },
  {
    id: 'a4',
    type: 'safety',
    severity: 'medium',
    title: 'Road Closure — Rohtang Pass',
    description: 'Rohtang Pass June 10–12 ke liye band rahega maintenance ke liye. Alternative route use karo.',
    destination: 'Manali, Himachal Pradesh',
    timestamp: '2026-05-08T10:00:00',
    actions: ['Alternative route dekho', 'HRTC helpline call karo', 'Itinerary update karo'],
    icon: '🛡️',
  },
  {
    id: 'a5',
    type: 'weather',
    severity: 'low',
    title: 'Perfect Weather — Ladakh',
    description: 'Ladakh mein July-August perfect weather hai. Pangong Lake aur Nubra Valley ke liye ideal time!',
    destination: 'Ladakh',
    timestamp: '2026-05-07T09:00:00',
    actions: ['Trip plan karo', 'Permit apply karo', 'Bike rent book karo'],
    icon: '☀️',
  },
];

export const communityPosts = [
  {
    id: 'p1',
    user: { name: 'Priya Sharma', avatar: 'https://randomuser.me/api/portraits/women/44.jpg', followers: 3240, verified: true },
    destination: 'Jaipur, Rajasthan',
    images: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',
    ],
    caption: 'Amber Fort ki ye shaam zindagi bhar yaad rahegi 🏰✨ Rajasthan ka har kona ek kahani sunata hai. Pink City ne dil jeet liya! #IncredibleIndia',
    likes: 4821,
    comments: 342,
    shares: 189,
    timestamp: '2026-05-08T18:30:00',
    tags: ['#Jaipur', '#Rajasthan', '#AmberFort', '#IncredibleIndia'],
    liked: false,
    saved: false,
  },
  {
    id: 'p2',
    user: { name: 'Arjun Mehta', avatar: 'https://randomuser.me/api/portraits/men/32.jpg', followers: 5670, verified: true },
    destination: 'Ladakh, J&K',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    caption: 'Pangong Lake ke kinare baith ke chai peena — ye feeling words mein nahi aa sakti 🏔️💙 Ladakh ek baar zaroor jao! #Ladakh #PangongLake',
    likes: 7234,
    comments: 521,
    shares: 298,
    timestamp: '2026-05-07T09:15:00',
    tags: ['#Ladakh', '#PangongLake', '#BikeTrip', '#Mountains'],
    liked: true,
    saved: true,
  },
  {
    id: 'p3',
    user: { name: 'Sneha Patel', avatar: 'https://randomuser.me/api/portraits/women/68.jpg', followers: 1892, verified: false },
    destination: 'Kerala Backwaters',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    ],
    caption: 'Houseboat mein ek raat — coconut trees, backwaters, aur stars 🌴⭐ Kerala truly is God\'s Own Country! Ayurveda massage ne toh soul refresh kar diya 🙏',
    likes: 3156,
    comments: 198,
    shares: 134,
    timestamp: '2026-05-06T14:45:00',
    tags: ['#Kerala', '#Backwaters', '#Houseboat', '#GodsOwnCountry'],
    liked: false,
    saved: true,
  },
  {
    id: 'p4',
    user: { name: 'Rahul Verma', avatar: 'https://randomuser.me/api/portraits/men/55.jpg', followers: 2340, verified: false },
    destination: 'Varanasi, UP',
    images: [
      'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80',
    ],
    caption: 'Ganga aarti dekh ke aankhein bhar aayi 🪔🙏 Varanasi sirf ek shehar nahi, ek anubhav hai. Har Indian ko ek baar zaroor aana chahiye! #Varanasi #GangaAarti',
    likes: 5892,
    comments: 412,
    shares: 267,
    timestamp: '2026-05-05T20:00:00',
    tags: ['#Varanasi', '#GangaAarti', '#Kashi', '#Spiritual'],
    liked: false,
    saved: false,
  },
];

export const priceTrends = [
  { month: 'Jan', flights: 4200, hotels: 2800, activities: 1200 },
  { month: 'Feb', flights: 3800, hotels: 2500, activities: 1100 },
  { month: 'Mar', flights: 5200, hotels: 3200, activities: 1500 },
  { month: 'Apr', flights: 6500, hotels: 4000, activities: 1800 },
  { month: 'May', flights: 5800, hotels: 3500, activities: 1600 },
  { month: 'Jun', flights: 4500, hotels: 2800, activities: 1300 },
  { month: 'Jul', flights: 5500, hotels: 3800, activities: 1700 },
  { month: 'Aug', flights: 5200, hotels: 3600, activities: 1600 },
  { month: 'Sep', flights: 4800, hotels: 3000, activities: 1400 },
  { month: 'Oct', flights: 6200, hotels: 4200, activities: 2000 },
  { month: 'Nov', flights: 7500, hotels: 5000, activities: 2400 },
  { month: 'Dec', flights: 8500, hotels: 6000, activities: 2800 },
];

export const crowdHeatmap = [
  { city: 'Goa', crowd: 92, trend: 'up' },
  { city: 'Jaipur', crowd: 75, trend: 'up' },
  { city: 'Manali', crowd: 68, trend: 'up' },
  { city: 'Kerala', crowd: 55, trend: 'stable' },
  { city: 'Varanasi', crowd: 82, trend: 'stable' },
  { city: 'Ladakh', crowd: 40, trend: 'down' },
  { city: 'Coorg', crowd: 45, trend: 'stable' },
  { city: 'Andaman', crowd: 35, trend: 'down' },
];

export const leaderboard = [
  { rank: 1, name: 'Vikram Singh', avatar: 'https://randomuser.me/api/portraits/men/10.jpg', trips: 52, states: 28, points: 15420 },
  { rank: 2, name: 'Ananya Krishnan', avatar: 'https://randomuser.me/api/portraits/women/11.jpg', trips: 44, states: 25, points: 13280 },
  { rank: 3, name: 'Rohan Gupta', avatar: 'https://randomuser.me/api/portraits/men/12.jpg', trips: 38, states: 22, points: 11640 },
  { rank: 4, name: 'Meera Nair', avatar: 'https://randomuser.me/api/portraits/women/13.jpg', trips: 31, states: 19, points: 9830 },
  { rank: 5, name: 'Aditya Joshi', avatar: 'https://randomuser.me/api/portraits/men/14.jpg', trips: 27, states: 16, points: 8180 },
];

export const suggestedPrompts = [
  '₹15,000 mein Rajasthan trip plan karo',
  'Kerala honeymoon package suggest karo',
  'Ladakh bike trip ke liye best route',
  'Goa mein budget-friendly stays',
  'Monsoon mein kahan jaana chahiye India mein?',
  'North East India hidden gems batao',
  'Family trip for Varanasi & Agra',
  'Solo travel tips for women in India',
];

export const weatherData = {
  city: 'Delhi',
  temp: 38,
  condition: 'Dhoop ke saath garmi',
  humidity: 45,
  wind: 18,
  icon: '☀️',
};

export const indianCities = [
  'Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata',
  'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow',
  'Kochi', 'Chandigarh', 'Bhopal', 'Indore', 'Surat',
];

export const tripTypes = [
  'Family Trip', 'Honeymoon', 'Solo Adventure', 'Friends Gang',
  'Pilgrimage', 'Hill Station', 'Beach Vacation', 'Heritage Tour',
  'Wildlife Safari', 'Backpacking',
];
